export const Site = [
  // ... adicione todos os itens da planilha Site

  {
    id: 1,
    Tipo_Objeto: "InTRAnet",
    Objeto: "http://164.163.239.234:5656/comprasedital",
  },
  { id: 2, Tipo_Objeto: "InTERnet", Objeto: "selcorp.com.br" },
  { id: 3, Tipo_Objeto: "InTERnet", Objeto: "portaldecomprasfsvc.com.br" },
  { id: 4, Tipo_Objeto: "InTERnet", Objeto: "ffm.br" },
  { id: 5, Tipo_Objeto: "InTERnet", Objeto: "ovg.org.br" },
  { id: 6, Tipo_Objeto: "InTERnet", Objeto: "app2.ammlicita.org.br" },
  { id: 7, Tipo_Objeto: "InTERnet", Objeto: "aquisicoes.seplag.mt.gov.br" },
  { id: 8, Tipo_Objeto: "E-mail", Objeto: "bancodepreco@educacaosalvador.net" },
  { id: 9, Tipo_Objeto: "InTERnet", Objeto: "pregaobanrisul.com.br" },
  { id: 10, Tipo_Objeto: "InTERnet", Objeto: "bllcompras.com" },
  { id: 11, Tipo_Objeto: "InTERnet", Objeto: "BNC Compras" },
  { id: 12, Tipo_Objeto: "InTERnet", Objeto: "comprasnet.ba.gov.br" },
  { id: 13, Tipo_Objeto: "InTERnet", Objeto: "compras.rj.gov.br" },
  { id: 14, Tipo_Objeto: "InTERnet", Objeto: "Compras BLL" },
  { id: 15, Tipo_Objeto: "InTERnet", Objeto: "COMPRAS BR" },
  { id: 16, Tipo_Objeto: "InTERnet", Objeto: "compras gov" },
  { id: 17, Tipo_Objeto: "InTERnet", Objeto: "compras.ma.gov.br" },
  { id: 18, Tipo_Objeto: "InTERnet", Objeto: "compras.mg.gov.br" },
  { id: 19, Tipo_Objeto: "InTERnet", Objeto: "comprasnet.ba.gov.br" },
  { id: 20, Tipo_Objeto: "InTERnet", Objeto: "compraspara.pa.gov.br" },
  { id: 21, Tipo_Objeto: "InTERnet", Objeto: "administracao.pr.gov.br" },
  { id: 22, Tipo_Objeto: "InTERnet", Objeto: "compras.barueri.sp.gov.br" },
  { id: 23, Tipo_Objeto: "InTERnet", Objeto: "compras.itaipu.gov.br" },
  { id: 24, Tipo_Objeto: "InTERnet", Objeto: "compras.m2atecnologia.com.br" },
  { id: 25, Tipo_Objeto: "InTERnet", Objeto: "compras.manaus.am.gov.br" },
  { id: 26, Tipo_Objeto: "InTERnet", Objeto: "compras.sistemafiergs" },
  { id: 27, Tipo_Objeto: "E-mail", Objeto: "compras@carmo.rj.gov.br" },
  { id: 28, Tipo_Objeto: "E-mail", Objeto: "compras@hcb.org.br " },
  { id: 29, Tipo_Objeto: "E-mail", Objeto: "compras@hmmc.org.br" },
  {
    id: 30,
    Tipo_Objeto: "E-mail",
    Objeto: "cotacao.sempre@salvador.ba.gov.br",
  },
  { id: 31, Tipo_Objeto: "E-mail", Objeto: "cotacao2.aguas@gmail.com" },
  { id: 32, Tipo_Objeto: "E-mail", Objeto: "dlc.licitacao@saude.ba.gov.br" },
  { id: 33, Tipo_Objeto: "InTERnet", Objeto: "e-lic.sc" },
  {
    id: 34,
    Tipo_Objeto: "InTERnet",
    Objeto: "egov.paradigmabs.com.br/sesc_senac_rs",
  },
  { id: 35, Tipo_Objeto: "InTERnet", Objeto: "fuabc.org.br" },
  {
    id: 36,
    Tipo_Objeto: "InTERnet",
    Objeto: "parceriassociais.sp.gov.br/OSC/OSC",
  },
  { id: 37, Tipo_Objeto: "InTERnet", Objeto: "apoiocotacoes.com.br" },
  {
    id: 38,
    Tipo_Objeto: "InTERnet",
    Objeto:
      "araraquaradaae.eportal.net.br/portal_licitacoes_externo_irrestrito",
  },
  { id: 39, Tipo_Objeto: "InTERnet", Objeto: "compras.m2atecnologia.com.br" },
  {
    id: 40,
    Tipo_Objeto: "InTERnet",
    Objeto: "cotacao.banpara.b.br/default.aspx",
  },
  { id: 41, Tipo_Objeto: "InTERnet", Objeto: "funev.org.br" },
  {
    id: 42,
    Tipo_Objeto: "InTERnet",
    Objeto: "santacruzdeminas.licitapp.com.br",
  },
  {
    id: 43,
    Tipo_Objeto: "InTERnet",
    Objeto: "portalcompras.ce.gov.br/fornecedores",
  },
  { id: 44, Tipo_Objeto: "InTERnet", Objeto: "sesc-rs.com.br/licitacoes" },
  { id: 45, Tipo_Objeto: "InTERnet", Objeto: "slicx.com.br" },
  { id: 46, Tipo_Objeto: "InTERnet", Objeto: "Licitações-e.com.br" },
  { id: 47, Tipo_Objeto: "InTERnet", Objeto: "Licitações-e2.bb.com.br" },
  { id: 48, Tipo_Objeto: "InTERnet", Objeto: "Licitamais Brasil" },
  { id: 49, Tipo_Objeto: "InTERnet", Objeto: "Licitanet" },
  { id: 50, Tipo_Objeto: "InTERnet", Objeto: "Licitar Digital" },
  {
    id: 51,
    Tipo_Objeto: "InTERnet",
    Objeto: "pbdocforms.pb.gov.br/servico/160",
  },
  { id: 52, Tipo_Objeto: "InTERnet", Objeto: "Novo BBM NET" },
  {
    id: 53,
    Tipo_Objeto: "E-mail",
    Objeto: "operacionalizacao.ucc@uberaba.mg.gov.br",
  },
  { id: 54, Tipo_Objeto: "InTERnet", Objeto: "PE Integrado" },
  { id: 55, Tipo_Objeto: "InTERnet", Objeto: "Portal de Compras Públicas" },
  { id: 56, Tipo_Objeto: "InTERnet", Objeto: "portal do fornecedor RS" },
  { id: 57, Tipo_Objeto: "InTERnet", Objeto: "Portal Petronect" },
  { id: 58, Tipo_Objeto: "InTERnet", Objeto: "portaldecompras.ce.gov.br" },
  { id: 59, Tipo_Objeto: "InTERnet", Objeto: "praiagrande.sp.gov.br" },
  { id: 60, Tipo_Objeto: "InTERnet", Objeto: "Presencial" },
  { id: 61, Tipo_Objeto: "InTERnet", Objeto: "publinexo" },
  { id: 62, Tipo_Objeto: "InTERnet", Objeto: "sefaz.ce" },
  { id: 63, Tipo_Objeto: "InTERnet", Objeto: "SIGA MS" },
  { id: 64, Tipo_Objeto: "InTERnet", Objeto: "SIGA RJ" },
  { id: 65, Tipo_Objeto: "InTERnet", Objeto: "siga.ap.gov.br" },
  {
    id: 66,
    Tipo_Objeto: "InTERnet",
    Objeto: "licitacoes-e2.bb.com.br/aop-inter-estatico/",
  },
  { id: 67, Tipo_Objeto: "E-mail", Objeto: "smscla.servicos06@gmail.com " },
  { id: 68, Tipo_Objeto: "E-mail", Objeto: "smscla.servicos08@gmail.com" },
  { id: 69, Tipo_Objeto: "E-mail", Objeto: "vander@fundahc.com.br" },
  { id: 70, Tipo_Objeto: "InTERnet", Objeto: "bertioga.sp.gov.br/licitacao" },
  { id: 71, Tipo_Objeto: "InTERnet", Objeto: "cabo.pe.gov.br" },
  { id: 72, Tipo_Objeto: "InTERnet", Objeto: "e-compras.am.gov.br." },
  { id: 73, Tipo_Objeto: "InTERnet", Objeto: "ffm.br" },
  { id: 74, Tipo_Objeto: "InTERnet", Objeto: "funed.mg.gov.br" },
  { id: 75, Tipo_Objeto: "InTERnet", Objeto: "licitamaisbrasil.com.br" },
  { id: 76, Tipo_Objeto: "InTERnet", Objeto: "ovg.org.br " },
  {
    id: 77,
    Tipo_Objeto: "InTERnet",
    Objeto: "parceriassociais.sp.gov.br/OSC/OSC/Chamamento",
  },
  { id: 78, Tipo_Objeto: "InTERnet", Objeto: "publinexo.com.br/privado/" },
  { id: 79, Tipo_Objeto: "InTERnet", Objeto: "selcorp.com.br " },
  { id: 80, Tipo_Objeto: "InTERnet", Objeto: "siga.ap.gov.br" },
];
